#!/usr/bin/perl
 
use strict;
use warnings;
 
use MyDatabase::Main;
 
my $schema = MyDatabase::Main->connect('dbi:Pg:dbname=ip_pool');
 
#  here's some of the SQL that is going to be generated by the schema
#  INSERT INTO artist VALUES (NULL,'Michael Jackson');
#  INSERT INTO artist VALUES (NULL,'Eminem');
 
my @ips;
my $i = 0;
push @ips, [sprintf('192.168.15.%d', $i)] while ++$i < 255;
$schema->populate('Ip', [
   [qw/ip/],
   @ips,
]);
